sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - "node_modules"

matrix:
  include:
    - os: linux
      node_js: "10"
      env: DEV=1
      stage: basic
    - os: linux
      node_js: "10"
      env: DEV=1
      stage: advanced
    - os: linux
      node_js: "10"
      env: DEV=1
      stage: advanced
    - os: osx
      node_js: "10"
      env: DEV=1
      stage: versions
    - os: linux
      node_js: "8"
      env: DEV=1
      stage: versions    
  fast_finish: true
